# Generated by Django 5.0.7 on 2024-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ordemservico_data_finalizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
